apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-manual
  namespace: kafka-poc
spec:
  template:
    spec:
      containers:
      - name: k6
        image: $YOUR_REGISTRY/k6-load-test:latest
        env:
        - name: ORDER_SERVICE_URL
          value: "http://IP-ADDRESS-HERE/api/orders"
      restartPolicy: Never
  backoffLimit: 1
